- name: Create ec2 and r53
  hosts: local
  connection: local
  vars:
    ami_id: ami-0220d79f3f480ecf5
    sg_id: sg-024615259cce53783
    zone_id: Z09903499ZOCINV74DX5
    domain-name: "daws-86s.fun"
    instances:
    - mongodb
  tasks:
  - name: create ec2 instances
    amazon.aws.ec2_instance:
      name: "{{ item }}"
      instance_type: t3.micro
      security_group: "{{ sg_id }}"
      image_id: "{{ ami_id }}"
      tags:
        Name: "{{ item }}"
    loop: "{{ instances }}"
    register: ec2_output
  - name: print the ec2-ec2_output
    ansible.builtin.debug:
      msg: "{{ ec2_output}}"              
 