[mongodb]
mongodb.devsecopsdaws-86s.fun
[redis]
redis.devsecopsdaws-86s.fun
[rabbitmq]
rabbitmq.devsecopsdaws-86s.fun
[mysql]
mysql.devsecopsdaws-86s.fun


[frontend]
3.208.18.29

[cart]
172.31.68.133

[local]
localhost

[all:vars]
ansible_user=ec2-ansible_user
ansible_password=DevOps321

